-- unload category table
UNLOAD ('SELECT * FROM public.category')
TO 's3://[BUCKETNAME]/category/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL OFF
ALLOWOVERWRITE;

-- unload date table
UNLOAD ('SELECT * FROM public.date')
TO 's3://[BUCKETNAME]/date/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL OFF
ALLOWOVERWRITE;

-- unload venue table
UNLOAD ('SELECT * FROM public.venue')
TO 's3://[BUCKETNAME]/venue/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL OFF
ALLOWOVERWRITE;

-- unload users table
UNLOAD ('SELECT * FROM public.users')
TO 's3://[BUCKETNAME]/users/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL ON
ALLOWOVERWRITE;

-- unload sales table
UNLOAD ('SELECT * FROM public.sales')
TO 's3://[BUCKETNAME]/sales/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL ON
ALLOWOVERWRITE;

-- unload listing table
UNLOAD ('SELECT * FROM public.listing')
TO 's3://[BUCKETNAME]/listing/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL ON
ALLOWOVERWRITE;

-- unload event table
UNLOAD ('SELECT * FROM public.event')
TO 's3://[BUCKETNAME]/event/'
IAM_ROLE 'INSERT-ARN'
PARQUET
PARALLEL OFF
ALLOWOVERWRITE;